- name: Install Android SDK + Accept Licenses FIX
      run: |
        sudo apt update
        sudo apt install -y wget unzip

        mkdir -p $HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk

        cd $HOME

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-*.zip -d $ANDROID_SDK_ROOT

        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/ || true

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" \
                   "platforms;android-33" \
                   "build-tools;34.0.0"
